snippet node-dockerfile-draft "dockerfile"
FROM node:7.10.0-alpine
MAINTAINER Halsn <xuhalsn@gmail.com>

ENV FOO="bar"

EXPOSE 8000

WORKDIR /app

# Copy source
ADD . ./

# Expose media folder
VOLUME /app/public/media

# Build
RUN npm i --prod && npm build

CMD npm start
endsnippet
