snippet node-dockerfile-draft "dockerfile"
FROM node:7.10.0-alpine
MAINTAINER Halsn <xuhalsn@gmail.com>

ENV FOO="bar"

EXPOSE 8000

WORKDIR /app

ADD . ./

VOLUME /app/public/media

RUN npm i --prod && npm build

CMD npm start
endsnippet
